# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mark1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(677, 573)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.i1 = QtWidgets.QCheckBox(Form)
        self.i1.setObjectName("i1")
        self.verticalLayout.addWidget(self.i1)
        self.i2 = QtWidgets.QCheckBox(Form)
        self.i2.setObjectName("i2")
        self.verticalLayout.addWidget(self.i2)
        self.i3 = QtWidgets.QCheckBox(Form)
        self.i3.setObjectName("i3")
        self.verticalLayout.addWidget(self.i3)
        self.i4 = QtWidgets.QCheckBox(Form)
        self.i4.setObjectName("i4")
        self.verticalLayout.addWidget(self.i4)
        self.i5 = QtWidgets.QCheckBox(Form)
        self.i5.setObjectName("i5")
        self.verticalLayout.addWidget(self.i5)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.p1 = QtWidgets.QLabel(Form)
        self.p1.setAlignment(QtCore.Qt.AlignCenter)
        self.p1.setObjectName("p1")
        self.verticalLayout_2.addWidget(self.p1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.p2 = QtWidgets.QLabel(Form)
        self.p2.setAlignment(QtCore.Qt.AlignCenter)
        self.p2.setObjectName("p2")
        self.verticalLayout_2.addWidget(self.p2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.p3 = QtWidgets.QLabel(Form)
        self.p3.setAlignment(QtCore.Qt.AlignCenter)
        self.p3.setObjectName("p3")
        self.verticalLayout_2.addWidget(self.p3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.p4 = QtWidgets.QLabel(Form)
        self.p4.setAlignment(QtCore.Qt.AlignCenter)
        self.p4.setObjectName("p4")
        self.verticalLayout_2.addWidget(self.p4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.p5 = QtWidgets.QLabel(Form)
        self.p5.setAlignment(QtCore.Qt.AlignCenter)
        self.p5.setObjectName("p5")
        self.verticalLayout_2.addWidget(self.p5)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.q1 = QtWidgets.QComboBox(Form)
        self.q1.setObjectName("q1")
        self.q1.addItem("")
        self.q1.addItem("")
        self.q1.addItem("")
        self.q1.addItem("")
        self.q1.addItem("")
        self.q1.addItem("")
        self.verticalLayout_3.addWidget(self.q1)
        self.q2 = QtWidgets.QComboBox(Form)
        self.q2.setObjectName("q2")
        self.q2.addItem("")
        self.q2.addItem("")
        self.q2.addItem("")
        self.q2.addItem("")
        self.q2.addItem("")
        self.verticalLayout_3.addWidget(self.q2)
        self.q3 = QtWidgets.QComboBox(Form)
        self.q3.setObjectName("q3")
        self.q3.addItem("")
        self.q3.addItem("")
        self.q3.addItem("")
        self.q3.addItem("")
        self.q3.addItem("")
        self.verticalLayout_3.addWidget(self.q3)
        self.q4 = QtWidgets.QComboBox(Form)
        self.q4.setObjectName("q4")
        self.q4.addItem("")
        self.q4.addItem("")
        self.q4.addItem("")
        self.q4.addItem("")
        self.q4.addItem("")
        self.verticalLayout_3.addWidget(self.q4)
        self.q5 = QtWidgets.QComboBox(Form)
        self.q5.setObjectName("q5")
        self.q5.addItem("")
        self.q5.addItem("")
        self.q5.addItem("")
        self.q5.addItem("")
        self.q5.addItem("")
        self.verticalLayout_3.addWidget(self.q5)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.pushButton_2.clicked.connect(self.generator)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.i1.setText(_translate("Form", "Burger"))
        self.i2.setText(_translate("Form", "Fries"))
        self.i3.setText(_translate("Form", "Chips"))
        self.i4.setText(_translate("Form", "Drinks"))
        self.i5.setText(_translate("Form", "Ice Cream"))
        self.p1.setText(_translate("Form", "30 per piece"))
        self.p2.setText(_translate("Form", "20 per box"))
        self.p3.setText(_translate("Form", "20 per packet"))
        self.p4.setText(_translate("Form", "20 per bottle"))
        self.p5.setText(_translate("Form", "15 per piece"))
        self.q1.setItemText(0, _translate("Form", "1"))
        self.q1.setItemText(1, _translate("Form", "2"))
        self.q1.setItemText(2, _translate("Form", "3"))
        self.q1.setItemText(3, _translate("Form", "4"))
        self.q1.setItemText(4, _translate("Form", "5"))
        self.q1.setItemText(5, _translate("Form", "6"))
        self.q2.setItemText(0, _translate("Form", "1"))
        self.q2.setItemText(1, _translate("Form", "2"))
        self.q2.setItemText(2, _translate("Form", "3"))
        self.q2.setItemText(3, _translate("Form", "4"))
        self.q2.setItemText(4, _translate("Form", "5"))
        self.q3.setItemText(0, _translate("Form", "1"))
        self.q3.setItemText(1, _translate("Form", "2"))
        self.q3.setItemText(2, _translate("Form", "3"))
        self.q3.setItemText(3, _translate("Form", "4"))
        self.q3.setItemText(4, _translate("Form", "5"))
        self.q4.setItemText(0, _translate("Form", "1"))
        self.q4.setItemText(1, _translate("Form", "2"))
        self.q4.setItemText(2, _translate("Form", "3"))
        self.q4.setItemText(3, _translate("Form", "4"))
        self.q4.setItemText(4, _translate("Form", "5"))
        self.q5.setItemText(0, _translate("Form", "1"))
        self.q5.setItemText(1, _translate("Form", "2"))
        self.q5.setItemText(2, _translate("Form", "3"))
        self.q5.setItemText(3, _translate("Form", "4"))
        self.q5.setItemText(4, _translate("Form", "5"))
        self.pushButton_2.setText(_translate("Form", "Generate Total"))
        self.pushButton.setText(_translate("Form", "Get reciept"))
        self.label_7.setText(_translate("Form", "Item Name"))
        self.label_6.setText(_translate("Form", "Unit price in rupees"))
        self.label_8.setText(_translate("Form", "Quantity"))

    def generator(self):
        import random

        x = str(random.randint(1000, 9999))
        cost = 0
        file1 = open("receipt" + x + ".txt", "w")

        # \n is placed to indicate EOL (End of Line)
        file1.write("Welcome to Hellfire kitchen !!!! \n")
        file1.write("Item      Unit_price   Quantity   Total_item_price \n")

        # to change file access modes

        if self.i1.isChecked() == True:
            cost1 = 30 * int(self.q1.currentText())
            file1.writelines("Burger        30        " + self.q1.currentText() + "         " + str(cost1) + "\n")
            cost = cost + cost1

        if self.i2.isChecked() == True:
            cost2 = 20 * int(self.q2.currentText())
            file1.writelines("Fries         20        " + self.q2.currentText() + "         " + str(cost2) + "\n")
            cost = cost + cost2

        if self.i3.isChecked() == True:
            cost3 = 20 * int(self.q3.currentText())
            file1.writelines("Chips         20        " + self.q3.currentText() + "         " + str(cost3) + "\n")
            cost = cost + cost3


        if self.i4.isChecked() == True:
            cost4 = 20 * int(self.q4.currentText())
            file1.writelines("Drinks        20        " + self.q4.currentText() + "         " + str(cost4) + "\n")
            cost = cost + cost4

        if self.i5.isChecked() == True:
            cost5 = 15 * int(self.q5.currentText())
            file1.writelines("Ice_Cream     15        " + self.q5.currentText() + "         " + str(cost5) + "\n")
            cost = cost + cost5

        print(cost)
        self.lineEdit.setText(str(cost) + " (Receipt no. " + x + " generated)")
        file1.writelines("Grand total=" + str(cost) + "\n")
        file1.writelines("Thank you for shopping with us. Come again!!")
        file1.close()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
